repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "--disable=R0913,R0917,R0914"
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args:
          - "--ignore-missing-imports"
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        types: [python]
